# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: generic
sudo: false

git:
  depth: 2

cache:
  pip: true

branches:
  only:
    - master
    - devel

env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.4
      env:
        - TOXENV=flake8
    - os: linux
      python: 2.7
      env:
        - TOXENV=py27
    - os: linux
      python: 3.4
      env:
        - TOXENV=py34
    - os: linux
      python: 3.5
      env:
        - TOXENV=py35
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36
    - os: osx
      language: objective-c
      python: 3.6
      env:
        - TOXENV=py36


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - travis_retry pip install -U pip setuptools wheel tox

# command to run tests, tox automatically uses TOXENV
script:
  - tox

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_organization }}/{{ cookiecutter.project_slug }}
    condition: $TOXENV == py27
{%- endif %}

notifications:
  email:
    on_success: never
    on_failure: never
